# Generated by Django 4.2.4 on 2023-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
